# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- features/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run Unit-Tests'
  inputs:
   command: test
   projects: '**/*test/*.csproj'
   arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: choco install docfx
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Install DocFX

- script: docfx metadata
  displayName: Build Documentation Meta-Data
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  workingDirectory: '$(Build.SourcesDirectory)/docfx'

- script: docfx build
  displayName: Build Documentation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  workingDirectory: '$(Build.SourcesDirectory)/docfx'

- task: GitHubPagesPublish@1
  inputs:
    docPath: '$(System.DefaultWorkingDirectory)\docs\*'
    githubusername: "secana"
    githubemail: 'azure-bot@penet.org'
    githubaccesstoken: $(token.github.penet.gh-pages)
    repositoryname: 'PeNet'
    branchname: 'gh-pages'
    commitmessage: 'Automated gh-pages update'
    cleanRepository: false

- task: DotNetCoreCLI@2
  displayName: 'Pack Nuget Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'pack'
    packagesToPack: '**\src\**\*.csproj'
    configuration: $(buildConfiguration)

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    nuGetFeedType: external
    allowPackageConflicts: true
    publishFeedCredentials: 'Nuget.org'
    packagesToPush: '$(build.artifactStagingDirectory)/*.*nupkg'