# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
#- task: DotNetCoreCLI@2
#  displayName: 'Run Unit-Tests'
#  inputs:
#    command: test
#    projects: '**/*test/*.csproj'
#    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
#
- task: DotNetCoreCLI@2
  displayName: 'Pack Nuget Package'
  inputs:
    command: 'pack'
    packagesToPack: '**\src\**\*.csproj'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Publish Nuget Package'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget.org'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'