# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'



steps:
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
# - powershell: |
#    dotnet tool install --tool-path ./tools --version 0.30.0 Cake.Tool
#   displayName: 'Install Cake'
# - powershell: ./tools/dotnet-cake --target=pack --verbosity=verbose
#   displayName: 'Build and package PeNet and PEditor'